import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-medicare-secondary-payer-lien-resolution",
  "engine": "recovery",
  "title": "Medicare Secondary Payer Lien Resolution",
  "shortTitle": "Medicare Secondary Payer Lien Resolution",
  "tagline": "Resolve Medicare conditional-payment obligations accurately while protecting settlement value and statutory compliance.",
  "industry": "Healthcare Lien Recovery",
  "buyer": "Law firms, self-insured employers, and claims administrators",
  "uiPort": 4660,
  "apiPort": 5660,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Medicare Secondary Payer Lien Resolution converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements in one accountable workflow. Resolve Medicare conditional-payment obligations accurately while protecting settlement value and statutory compliance.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Medicare Secondary Payer Lien Resolution evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("beneficiary-eligibility-verification","MSP01","Beneficiary eligibility verification","Execute beneficiary eligibility verification using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed beneficiary eligibility verification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Beneficiary eligibility verification Reference","text","MSP01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("liability-event-registry","MSP02","Liability event registry","Execute liability event registry using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed liability event registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Liability event registry Reference","text","MSP02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("conditional-payment-ingestion","MSP03","Conditional payment ingestion","Execute conditional payment ingestion using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed conditional payment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Conditional payment ingestion Reference","text","MSP03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("claim-relatedness-review","MSP04","Claim relatedness review","Execute claim relatedness review using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed claim relatedness review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Claim relatedness review Reference","text","MSP04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("unrelated-claim-dispute","MSP05","Unrelated claim dispute","Execute unrelated claim dispute using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed unrelated claim dispute decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Unrelated claim dispute Reference","text","MSP05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("procurement-cost-allocation","MSP06","Procurement cost allocation","Execute procurement cost allocation using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed procurement cost allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Procurement cost allocation Reference","text","MSP06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("demand-amount-calculation","MSP07","Demand amount calculation","Execute demand amount calculation using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed demand amount calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Demand amount calculation Reference","text","MSP07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("settlement-reporting-control","MSP08","Settlement reporting control","Execute settlement reporting control using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed settlement reporting control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Settlement reporting control Reference","text","MSP08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("section-111-evidence","MSP09","Section 111 evidence","Execute section 111 evidence using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed section 111 evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Section 111 evidence Reference","text","MSP09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("final-demand-tracking","MSP10","Final demand tracking","Execute final demand tracking using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed final demand tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Final demand tracking Reference","text","MSP10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("appeal-waiver-workflow","MSP11","Appeal waiver workflow","Execute appeal waiver workflow using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed appeal waiver workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Appeal waiver workflow Reference","text","MSP11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("payment-reconciliation","MSP12","Payment reconciliation","Execute payment reconciliation using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Payment reconciliation Reference","text","MSP12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("release-letter-evidence","MSP13","Release letter evidence","Execute release letter evidence using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed release letter evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Release letter evidence Reference","text","MSP13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("settlement-reserve-forecast","MSP14","Settlement reserve forecast","Execute settlement reserve forecast using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed settlement reserve forecast decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Settlement reserve forecast Reference","text","MSP14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]}),
feature("case-outcome-analytics","MSP15","Case outcome analytics","Execute case outcome analytics using eligibility, conditional payments, claims, liability events, settlement terms, procurement costs, demand letters, disputes, and reimbursements.","Produce a governed case outcome analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Beneficiary / Settlement","text","Beneficiary / Settlement · Standard Case"],["caseReference","Case outcome analytics Reference","text","MSP15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",741250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",896913],["domainDriver","Case Type","select","Liability",["Liability","Workers compensation","No-fault"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Beneficiary eligibility verification case","Liability event registry case","Conditional payment ingestion case","Claim relatedness review case","Unrelated claim dispute case"]})
]);
